### ISSUE TITLE
Cannot capture event 

### ISSUE THREAD

**Issue by NoMaillard** [reecelucas/react-use-hotkeys#14]
Hello,

thank you for this hook, i find it really useful.

howerver, it is not possible to add event listener on the capturing phase see https://javascript.info/bubbling-and-capturing

it would be great fi it was possible to change the signature of the hook to this:

```ts
const useHotkeys = (
  hotkeys: string | string[],
  callback: (event: KeyboardEvent) => void,
  options?: boolean | AddEventListenerOptions
) => {
    
    // business logic ...

    window.addEventListener('keydown', onKeydown, options);

    return () => {
      window.removeEventListener('keydown', onKeydown, options);
    };
}
```

**Comment by reecelucas** [comment]
Hi @NoMaillard, 

That seems like a sensible addition, I can add this in. I think `eventListenerOptions` might be a more descriptive name.

Out of interest what use case are you currently finding you need this for? It might be useful for me to surface it in the README as an example.

Thanks!

**Comment by NoMaillard** [comment]
Hi @reecelucas , thanks for the quick reply

the use case for this feature is for when an event listener in the target phase (or in the bubbling phase before the document) calls `stopPropagation()`.

my specific use case is for the material-ui autocomplete component.

i want to lose the focus on `Escape`, but since the options list is shown, the escape event closes the list, and the propagation is stopped by the component, so i have to press escape twice.

 listening to the event on the capturing phase will allow me to loose the focus while allowing the component to do it's thing

**Comment by reecelucas** [comment]
@NoMaillard closing as this is now possible in v1.3.0 😄
