### ISSUE TITLE
Not working with "?"

### ISSUE THREAD

**Issue by spyx08** [reecelucas/react-use-hotkeys#16]
I tried to attach a hotkey on "?" using 

`useHotkeys("?",() => console.log("ok"))`

also tried with `{capture:true}` but the callback isn't fired

Any idea ?  

**UPDATE**

Can be fixed by listening on "*" and with custom check. But I don't like this approach

**Comment by reecelucas** [comment]
@spyx08 in order to trigger on "?" you can pass "Shift+?", which is what the user would have to press in order to select "?". You can try it out here https://keycode.info/ 😄.

**Comment by spyx08** [comment]
@reecelucas I tried that way too, the problem is that the shortcut is fired while typing "?" on inputs. 
I wanted to avoid to check the event target by using a library.

**Comment by reecelucas** [comment]
@spyx08 could you provide a minimal reproduction in [codesandbox](https://codesandbox.io/s/), or similar?
