### ISSUE TITLE
The lib doesn't accept React 17.x as peerDependency

### ISSUE THREAD

**Issue by Onra** [reecelucas/react-use-hotkeys#17]
React team recently released [major version 17](https://github.com/facebook/react/blob/master/CHANGELOG.md#1700-october-20-2020) of their library.
Currently, the `peerDependency` to `react` is defined as `^16.8.0`.
Would it be possible to update the `peerDependency` in the `package.json` file?

**Comment by reecelucas** [comment]
@Onra, sure, I'll take a look 👍

**Comment by reecelucas** [comment]
@Onra closing now that `v1.3.1` accepts `>=16.8.0`

**Comment by Onra** [comment]
Many thanks for the quick update @reecelucas ! 👍
