### ISSUE TITLE
keys as string[] not allowed in typescript

### ISSUE THREAD

**Issue by SO-Eng** [reecelucas/react-use-hotkeys#34]
Hi, 

I'm trying to set multiple key combinations in my project, what is completely typed.
As in your example below it should be possible.

_// Multiple key combinations mapped to the same callback
useHotkeys(['Control+z', 'Meta+z'], () => {
  console.log('Some action');
});_

But with typing it is not as you can see in useHotkeys.d.ts in line 15/16/17. (keys: string, callback: .... )
`export declare function useHotkeys<T extends Element>(keys: string, callback: KeyHandler, options?: Options): React.MutableRefObject<T | null>;
`
I guess it should be: ...(keys: string | string[], callback: ...)

Or should I extend useHotkeys.d.ts with my own rules?

Greetings
Markus

**Comment by reecelucas** [comment]
Hi Markus. You're correct, there seems to be an issue with the generated types, since the `src` types are correct (`string | string[]`). I'll have a look into what's gone askew with the declaration file 👍

**Comment by reecelucas** [comment]
Closing this for now but if you're still encountering issues let me know 👍
