### ISSUE TITLE
Listen to "+" being pressed not possible

### ISSUE THREAD

**Issue by desombre** [reecelucas/react-use-hotkeys#45]
I tried to listen to the plus symbol being pressed. On the numpad it works fine, but the non-numpad plus was not picked up. I tried using: `  useHotkeys('plus, "+", +', () =>...);`.
Any ideas?

**Comment by reecelucas** [comment]
@desombre yeah this doesn't appear to be supported at the moment. The special characters don't work in a modifier sequence: `Shift++`, which would be required to match `+`. I'll see about adding support.

**Comment by reecelucas** [comment]
@desombre this is now fixed with `v1.3.2`. You can use `Shift++` or `Shift + +` to target the `+` key on the non-numpad. I'll close this now, but please reopen if the issue persists.
