### ISSUE TITLE
react-use-hotkeys v1.3.2 stopped working in Safari

### ISSUE THREAD

**Issue by marc-se** [reecelucas/react-use-hotkeys#47]
First: Thanks for this awesome hook!

After updating the version from 1.3.1 to 1.3.2 we noticed that the useHotkeys hook stopped working in Safari (tested with 15.4).

Cause there is a client side dependency involved, I need to use `nextjs` (v12.1.6) dynamic imports like this:

`const DynamicHotkeys = dynamic(() => import("./PlayerHotkeys"), {
  ssr: false,
});`

The PlayerHotkeys component looks as simple as that:

```
  const PlayerHotkeys = ({
      requestToggleMute
    }: Props) => {

    useHotkeys("m", () => {
        requestToggleMute();
    });

   // more hotkeys below
  
    return <></>;
  };
```

I wasn't able to see any logs in the console. The component just returned nothing (tried to return a simple string in the fragment, and I also tried to do some logging before and after the useHotkeys hooks, but also no output). As soon as I downgraded to v1.3.1 everything worked like before. Maybe it's due to an dependency update? Any idea? Just wanted to address the issue. 

Thanks for your great work!

**Comment by reecelucas** [comment]
Hi @marc-se, thanks for reporting this. I'll take a look in Safari and see if I can debug. I'll begin by using the hook without any dynamic imports to rule out the possibility it's just an issue with just dynamic imports.

**Comment by reecelucas** [comment]
@marc-se `v.1.3.3` includes a fix. Safari doesn't support negative lookbehind regex, which was introduced in `v.1.3.2`. This has been removed and a more broadly-supported alternative used instead. Let me know if you still have issues! In the meantime I'll close this issue 👍

**Comment by marc-se** [comment]
> @marc-se `v.1.3.3` includes a fix. Safari doesn't support negative lookbehind regex, which was introduced in `v1.3.2`. This has been removed and a more broadly-supported alternative used instead. Let me know if you still have issues! In the meantime I'll close this issue 👍

works like a charm! thank you for your fast reply :)
