### ISSUE TITLE
Dependency on `shim-keyboard-event-key` creates SSR error

### ISSUE THREAD

**Issue by chandlervdw** [reecelucas/react-use-hotkeys#49]
I'm using this package on a Gatsby site, which uses server-side rendering (SSR). Consequently, some issues can arise when `window` is reference as `window` is `undefined` on the server. I believe the same is true for `self`.

The issues comes from `shim-keyboard-event-key/index.js:4:1`:
```
(function() {
  "use strict"

  if (!self.document) return
```
`ReferenceError: self is not defined`

----

Is there a workaround for this? Since I'm utilizing the `useHotKeys` hook, I'm not sure there's a way to conditionally call this.

**Comment by chandlervdw** [comment]
https://github.com/shvaikalesh/shim-keyboard-event-key/pull/2

**Comment by reecelucas** [comment]
@chandlervdw this should now be fixed in `v.1.3.4`. I decided to vendor https://github.com/shvaikalesh/shim-keyboard-event-key since it doesn't appear to be actively maintained and it's a tiny package. Let me know if there are any issues 👍
