### ISSUE TITLE
Chord hotkeys should be triggered when the latest keys pressed are a match and not only when all the keys match

### ISSUE THREAD

**Issue by bogdbo** [reecelucas/react-use-hotkeys#55]
eg. having a hotkey on `g g`

if I press `f g g` nothing will happen. 

If I wait until the key tracking is cleared and then press `g g` it will work.

Suggestion:

As soon as the last keys match a chord definition, trigger the hotkey.

**Comment by reecelucas** [comment]
Hi @bogdbo. I think this suggestion might lead to some confusing behaviour. A consumer of this library might want to bind a callback to `f g g` and to `g g`, but this approach would mean both callbacks would fire when `f g g` was keyed by the user, which probably isn't what the consumer would expect. The key timer prevents this from happening. Let me know if I've misunderstood though 👍
