### ISSUE TITLE
Ability to conditionaly disable hotkeys

### ISSUE THREAD

**Issue by bogdbo** [reecelucas/react-use-hotkeys#56]
Since this is a hook it's not easily possible to disable hotkeys

Suggestions, the hook should accept an `enabled` param and act accordingly

**Comment by reecelucas** [comment]
Hi @bogdbo this suggestion makes sense. I'll start working on an update 👍

**Comment by reecelucas** [comment]
@bogdbo this issue is now fixed in `v2.0.0`. Closing this issue, but please let me know if you encounter any further issues.
