### ISSUE TITLE
Disable hotkeys in input fields

### ISSUE THREAD

**Issue by bogdbo** [reecelucas/react-use-hotkeys#57]
There should be a way to disable hotkeys when writing in input fields

Suggestion: event.currentTarget might contain the dom element

**Comment by reecelucas** [comment]
Hi @bogdbo this suggestion makes sense. I'll start working on an update 👍

**Comment by reecelucas** [comment]
@bogdbo this issue is now fixed in `v2.0.0`. Closing this issue, but please let me know if you encounter any further issues.
