### ISSUE TITLE
What is the correct way to do this?

### ISSUE THREAD

**Issue by colindotfun** [reecelucas/react-use-hotkeys#62]
In this case, if I do meta shift k, the menu opens, and the alert is not triggered.

Is this an incorrect approach?

```
useHotkeys("Meta+k", () => setShowCommandPalette(true));
useHotkeys("Meta+Shift+k", () => alert("link"));
```

**Comment by colindotfun** [comment]
In fact, it does not work for "Meta+Shift+z" either, which is straight from the README:

`useHotkeys("Meta+Shift+k", () => alert("link"));`

**Comment by colindotfun** [comment]
Actually, I noticed that the order matters (not sure why):

will work:
```
  useHotkeys("Meta+Shift+k", () => alert("link"));
  useHotkeys("Meta+k", () => setShowCommandPalette(true));
```

will not work:
```
  useHotkeys("Meta+k", () => setShowCommandPalette(true));
  useHotkeys("Meta+Shift+z", () => alert("link"));
```

**Comment by colindotfun** [comment]
Nope spoke too soon -- not working, and not sure why :(

**Comment by reecelucas** [comment]
Hi @colinricardo, I can't reproduce this issue. I've created a minimal reproduction in code sandbox based on your example above. Please check out https://codesandbox.io/s/solitary-moon-ssdpt3?file=/src/App.js. Pressing `k` while holding down the command key shows the expected command palette. Please let me know if this doesn't clarify things.
